const constants = {
  GET_COLLECTION_ENTRY: 'GET_COLLECTION_ENTRY',
  GET_COLLECTION_LIST: 'GET_COLLECTION_LIST',
  GET_COLLECTION_SHOW: 'GET_COLLECTION_SHOW',
  GET_FAVORITE_LIST: 'GET_FAVORITE_LIST',
  GET_HOME_TIMELINE: 'GET_HOME_TIMELINE',
  GET_MENTION_TIMELINE: 'GET_MENTION_TIMELINE',
  GET_STATUS_UPDATE: 'GET_STATUS_UPDATE',
  GET_STATUS_USER_TIMELINE: 'GET_STATUS_USER_TIMELINE'
 }
 export default constants